/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "uart.h"
#include "Time_Out.h"

//#define TX
#define RX



int main(void)
{

#ifdef TX
	uint8_t tx_buffer [] = "Hello UART!";
#endif
#ifdef RX

	uint8_t rx_buffer[12];
#endif
/* Enable the clock for USART2 */
	UART_ClockEnable(USART2);

/* Enable the clock for Ports A and D */
	GPIO_ClockEnable(GPIOA);
	GPIO_ClockEnable(GPIOD);


/* --- GPIO Configuration ---*/
	GPIO_Init(GPIOA, AF, NPUPD, PP, Pin2);
	GPIO_Init(GPIOA, AF, PU, PP, Pin3);
	GPIO_SetAlternate(GPIOA, Pin2, AF7);
	GPIO_SetAlternate(GPIOA, Pin3, AF7);
	GPIO_Init(GPIOD, OUTPUT, NPUPD, PP, Pin12);
	GPIO_Init(GPIOD, OUTPUT, NPUPD, PP, Pin13);
	GPIO_Init(GPIOD, OUTPUT, NPUPD, PP, Pin14);
	GPIO_Init(GPIOD, OUTPUT, NPUPD, PP, Pin15);

/* --- Initialise uart2 ---*/
#ifdef TX
    UART_Init(USART2, 9600, TE); //Transmitter
#endif

#ifdef RX
    UART_Init(USART2, 9600, RE); //Receiver
#endif


	while(1)
	{

		GPIO_WriteBit(GPIOD, GPIO_Pin_15, 0x01);
		GPIO_WriteBit(GPIOD, GPIO_Pin_13, 0x01);
#ifdef TX
        UART_SendBuffer(USART2,  tx_buffer, sizeof(tx_buffer));
#endif

#ifdef RX
        TypedefStatus status = UART_ReceiveBuffer(USART2, rx_buffer, sizeof(rx_buffer), 1000);

        if (status == OK) {
            GPIO_WriteBit(GPIOD, GPIO_Pin_12, 0x01); // success LED
        } else {
            GPIO_WriteBit(GPIOD, GPIO_Pin_14, 0x01); // error LED
        }
#endif

        Delay(0x4FFFFF);


	}


}
/**
  * @brief  Inserts a delay time.
  * @param  nCount: specifies the delay time length.
  * @retval None
  */
void Delay(volatile unsigned  int  nCount)
{
  for(; nCount != 0; nCount--);
}
